export { Background } from "./components/Background.js"
export { Cursor, type CursorKeyframe } from "./components/Cursor.js"
export { ClickRipple } from "./components/ClickRipple.js"
export { ZoomLayer, type BBox } from "./components/ZoomLayer.js"
export { Callout } from "./components/Callout.js"
export { Caption } from "./components/Caption.js"
export { buildTimeline, type Timeline } from "./timeline.js"
export { BeaconShowcase, type BeaconShowcaseProps } from "./composition.js"
export { RemotionRoot } from "./Root.js"
